#!/bin/sh
# Launch SliTaz default Text Editor.
#

. /etc/slitaz/applications.conf

USER_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/slitaz/applications.conf"
[ -f  $USER_CONFIG ] && . $USER_CONFIG

if [ -z "$XAUTHORITY" ]; then
	# console session
	EXEC="$EDITOR"
else
	# Xorg session
	EXEC="terminal -e $EDITOR"
fi

case $EDITOR in
	emacs|joe|jed|ht|le|nano|vi*) $EXEC $@ ;;
	mcedit) $EXEC -a -S nicedark $@ ;;
	*) exec setsid $EDITOR $@ ;;
esac

exit 0
