#!/bin/bash
paket="$1"
dokunulmaz="/etc/dokunulmaz"


#while IFS='' read -r line || [[ -n "$line" ]]; do
icerik_sil(){
	while read -r dosya
	do
		if [[ $(grep -c $dosya $dokunulmaz) -eq 0 ]]; then
			echo /$dosya
			#rm -r -f /$dosya
		fi
	done < /var/lib/pkg/DB/"$paket"/files
}

icerik_sil && rm -r -f /var/lib/pkg/DB/"$paket"

# kullanım: 

# paket_sil nano
