#!/bin/bash
versiyon="0.1"
paketdepo="/depo/paketler/"
sunucu="192.168.3.193:8000/paketdepo/"
ikaynak=""

icerik_ekle(){
	echo $1
	paketad=`echo "$1" | cut -d'#' -f1`	
	paketad=`basename $paketad`
	echo $paketad" paketi kuruluyor."
	mkdir -p /var/lib/pkg/DB/"$paketad" &&
	tar xf $1 -C /  && 
	mv /.MTREE /var/lib/pkg/DB/"$paketad"/files &&
	mv /.META /var/lib/pkg/DB/"$paketad"/META &&
	echo $paketad" paketi kuruldu."
}

paketvt_guncelle(){
	if wget -P /tmp -q "$sunucu""paket.vt" > /dev/null; then
		echo "paket veritabanı guncellenıyor." "$paketdepo""paket.vt"
		if [ -f "$paketdepo""paket.vt" ];then
			mv "$paketdepo""paket.vt" "$paketdepo""paket.vt.eski"
		fi
		wget -P "$paketdepo" "$sunucu""paket.vt"
		rm /tmp/paket.vt*
		exit 1
	fi
	echo "paket veritabanı guncelleme olumsuz."
}

ayarlar() {
	while [ "$1" ]; do
		case $1 in
			-ak|--agdan)
				ikaynak="ag" ;;
			-yk|--yerelden)
				ikaynak="yerel" ;;
			-vtg|--vt-guncelle)
				paketvt_guncelle ;;
			-cf|--config-file)
				if [ ! "$2" ]; then
					echo "ayardosyası gerek $1"
					exit 1
				fi
				ayar_dosyasi="$2"
				shift ;;
			-v|--version)
				echo "$versiyon"
				exit 0 ;;
			-h|--help)
				print_help
				exit 0 ;;
			
		esac
		shift
	done
}
ana(){
ayarlar "$@"

if [ "$ikaynak" = "ag" ]; then
	echo "agdan cekiliyor:" "$2"
	pkt=`cat "$paketdepo""paket.vt" | grep -w "$2" | cut -d' ' -f2` 
	if [ ! -z "$pkt" -a "$pkt" != "" ]; then
		cpaket="${pkt/'#'/'%23'}"
		echo "$sunucu$cpaket"
		#paket sunucuda varsa
		if wget -P /tmp -q "$sunucu$cpaket" > /dev/null; then
			#wget -nc -P "$paketdepo" "$sunucu$cpaket"
			mv /tmp/$pkt "$paketdepo"
			icerik_ekle "$paketdepo$pkt"
			exit 1
		fi
	fi
	echo "paket sunucuda bulunamadı!"
fi

if [ "$ikaynak" = "yerel" ]; then
	pkontrol=`basename $2 | grep -w "mps.xz"`
	if [ ! -z "$pkontrol" -a "$pkontrol" != "" ]; then
		icerik_ekle "$2"
	fi
fi

}
ana "$@"
# kullanım: 

# paketkur nano.mps.xz
